language: node_js
node_js: node

notifications:
  email:
    on_failure: change
    on_success: change

before_install: yarn global add gatsby

script: yarn build

deploy:
  skip_cleanup: true
  local_dir: public
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "courtney-pattison"
  on:
    branch: master