language: node_js
node_js: node

notifications:
  email:
    on_failure: change
    on_success: change

before_install:
  - npm install -g gulp
  - sudo apt install imagemagick
  - wget http://download.xnview.com/NConvert-linux64.tgz
  - tar xzf NConvert-linux64.tgz
  - export PATH=$PATH:$PWD/NConvert

install: npm install

os: linux

script: gulp

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "courtney-pattison"
  on:
    branch: master